package apis

// DO NOT EDIT - generated by aliasgen tool (github.com/rhuairahrighairidh/aliasgen)

import (
	"github.com/cbonoz/cosmos20/x/apis/keeper"
	"github.com/cbonoz/cosmos20/x/apis/types"
)

const (
	AttributeRequestID           = types.AttributeRequestID
	AttributeValueCategory      = types.AttributeValueCategory
	// DefaultParamspace           = types.DefaultParamspace
y
	ModuleName                  = types.ModuleName
	QuerierRoute                = types.QuerierRoute
	QueryGetParams              = types.QueryGetParams
	QueryRequests                = types.QueryRequests
s
	RouterKey                   = types.RouterKey
	StoreKey                    = types.StoreKey
	TypeMsgPostResponse            = types.TypeMsgPostResponse
)

var (
	// function aliases
	NewKeeper                  = keeper.NewKeeper
	NewQuerier                 = keeper.NewQuerier
	DefaultGenesisState        = types.DefaultGenesisState
	DefaultParams              = types.DefaultParams
	NewGenesisState            = types.NewGenesisState
	NewRequest                  = types.NewRequest
	NewMsgPostResponse            = types.NewMsgPostResponse
	NewParams                  = types.NewParams
	NewQueryWithRequestIDParams = types.NewQueryWithRequestIDParams
	ParamKeyTable              = types.ParamKeyTable
	RegisterCodec              = types.RegisterCodec

	// variable aliases
	DefaultRequests     = types.DefaultRequests
	ModuleCdc                  = types.ModuleCdc
)

type (
	Keeper                  = keeper.Keeper
	GenesisState            = types.GenesisState
	Request                  = types.Request
	Requests                 = types.Requests
	Params                  = types.Params
	QueryWithRequestIDParams = types.QueryWithRequestIDParams
	SortDecs                = types.SortDecs
)
