package apis

// DO NOT EDIT - generated by aliasgen tool (github.com/rhuairahrighairidh/aliasgen)

import (
	"github.com/cbonoz/cosmos20/x/apis/keeper"
	"github.com/cbonoz/cosmos20/x/apis/types"
)

const (
	AttributeExpiry             = types.AttributeExpiry
	AttributeRequestID           = types.AttributeRequestID
	AttributeRequestPrice        = types.AttributeRequestPrice
	AttributeOracle             = types.AttributeOracle
	AttributeValueCategory      = types.AttributeValueCategory
	DefaultParamspace           = types.DefaultParamspace
	EventTypeRequestPriceUpdated = types.EventTypeRequestPriceUpdated
	EventTypeNoValidPrices      = types.EventTypeNoValidPrices
	EventTypeOracleUpdatedPrice = types.EventTypeOracleUpdatedPrice
	MaxExpiry                   = types.MaxExpiry
	ModuleName                  = types.ModuleName
	QuerierRoute                = types.QuerierRoute
	QueryGetParams              = types.QueryGetParams
	QueryRequests                = types.QueryRequests
	QueryOracles                = types.QueryOracles
	QueryPrice                  = types.QueryPrice
	QueryRawPrices              = types.QueryRawPrices
	RouterKey                   = types.RouterKey
	StoreKey                    = types.StoreKey
	TypeMsgPostPrice            = types.TypeMsgPostPrice
)

var (
	// function aliases
	NewKeeper                  = keeper.NewKeeper
	NewQuerier                 = keeper.NewQuerier
	CurrentPriceKey            = types.CurrentPriceKey
	DefaultGenesisState        = types.DefaultGenesisState
	DefaultParams              = types.DefaultParams
	NewCurrentPrice            = types.NewCurrentPrice
	NewGenesisState            = types.NewGenesisState
	NewRequest                  = types.NewRequest
	NewMsgPostPrice            = types.NewMsgPostPrice
	NewParams                  = types.NewParams
	NewPostedPrice             = types.NewPostedPrice
	NewQueryWithRequestIDParams = types.NewQueryWithRequestIDParams
	ParamKeyTable              = types.ParamKeyTable
	RawPriceKey                = types.RawPriceKey
	RegisterCodec              = types.RegisterCodec

	// variable aliases
	CurrentPricePrefix = types.CurrentPricePrefix
	DefaultRequests     = types.DefaultRequests
	ErrAssetNotFound   = types.ErrAssetNotFound
	ErrEmptyInput      = types.ErrEmptyInput
	ErrExpired         = types.ErrExpired
	ErrInvalidRequest   = types.ErrInvalidRequest
	ErrInvalidOracle   = types.ErrInvalidOracle
	ErrNoValidPrice    = types.ErrNoValidPrice
	KeyRequests         = types.KeyRequests
	ModuleCdc          = types.ModuleCdc
	RawPriceFeedPrefix = types.RawPriceFeedPrefix
)

type (
	Keeper                  = keeper.Keeper
	CurrentPrice            = types.CurrentPrice
	CurrentPrices           = types.CurrentPrices
	GenesisState            = types.GenesisState
	Request                  = types.Request
	Requests                 = types.Requests
	MsgPostPrice            = types.MsgPostPrice
	Params                  = types.Params
	PostedPrice             = types.PostedPrice
	PostedPrices            = types.PostedPrices
	QueryWithRequestIDParams = types.QueryWithRequestIDParams
	SortDecs                = types.SortDecs
)
